### PR TITLE
feat: remove placeholder functionality from framework

### PR DESCRIPTION
**Pull request by hetangmodi-crest**
ADDON-71391
Removes the placeholder related functionalities and the test cases present.
Users would no longer be able to use the `get_placeholder_value` property for their test cases.

**NOTE:** This PR can be merged once UCC 5.48.0 is released and updating the same version for this repo.

BREAKING CHANGE: remove placeholder functionality

### CODE REVIEW

**Comment by mkolasinski-splunk** [comment]
As adoption of SmartX v4 is 0%, I don't think we need to make breaking change.

**Comment by hetangmodi-crest** [comment]
Fixed the failing test cases.

**Pull request merged**
